### ISSUE TITLE
DateTime columns fail on Write if SchemaElement is set to nullable

### ISSUE THREAD

**Issue by moggy001** [elastacloud/parquet-dotnet#234] opened 2017-10-05 04:49 UTC
If rows are added to a DataSet where some have a null value in a DateTime column (which causes that SchemaElement to be marked as nullable) while others have a valid DateTime in that column then the Write method will fail.

Column definition:

new SchemaElement<DateTime>(colInfo.GetColumnName());

Message:

The value "28/06/2017 00:00:00" is not of type "System.DateTimeOffset" and cannot be used in this generic collection.
Parameter name: value

Stack trace:

   at System.ThrowHelper.ThrowWrongValueTypeArgumentException(Object value, Type targetType)
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at Parquet.ParquetWriter.CreateDefinitions(IList values, SchemaElement schema, IList& nonNullableValues, List`1& definitions)
   at Parquet.ParquetWriter.WriteValues(SchemaElement schema, IList values, PageHeader ph, CompressionMethod compression, ColumnStats stats)
   at Parquet.ParquetWriter.Write(SchemaElement schema, IList values, CompressionMethod compression, ColumnStats stats)
   at Parquet.ParquetWriter.<>c__DisplayClass11_0.<Write>b__0(SchemaElement c)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Parquet.ParquetWriter.Write(DataSet dataSet, CompressionMethod compression, Boolean append)

**Comment by aloneguid** [comment] 2017-10-05 15:05
@moggy001 can you show the code you're using to reproduce this?

**Comment by aloneguid** [comment] 2017-10-10 15:30
Closing as can't reproduce this. Please feel free to reopen when more info is available.

**Closed by aloneguid** 2017-10-10 15:30 UTC
Labels: cannot reproduce

**Comment by moggy001** [comment] 2017-10-12 10:17
Code to reproduce as follows:

            var schemaElements = new List<SchemaElement>();
            schemaElements.Add(new SchemaElement<string>("primary-key"));
            schemaElements.Add(new SchemaElement<DateTime>("as-at-date"));

            var ds = new DataSet(schemaElements);

            // row 1
            var objData1 = new List<object>(schemaElements.Count);
            objData1.Add(Guid.NewGuid().ToString());
            objData1.Add(DateTime.UtcNow.AddDays(-5));
            ds.Add(new Row(objData1));

            // row 2
            var objData2 = new List<object>(schemaElements.Count);
            objData2.Add(Guid.NewGuid().ToString());
            objData2.Add(DateTime.UtcNow);
            ds.Add(new Row(objData2));

            // row 3
            var objData3 = new List<object>(schemaElements.Count);
            objData3.Add(Guid.NewGuid().ToString());
            objData3.Add(null);
            ds.Add(new Row(objData3));

            using (var memStream = new MemoryStream())
            {
                using (var writer = new ParquetWriter(memStream))
                {
                    writer.Write(ds);
                }
            }

**Comment by moggy001** [comment] 2017-10-12 10:17
@aloneguid , please would you reopen and have a look? Thanks

**Comment by moggy001** [comment] 2017-10-12 10:20
If row 3 in the sample code is modified to have a valid DateTime value then all works ok.
I have worked around the problem by using DateTimeSchemaElement instead and converting all valid (non-null) DateTime values to DateTimeOffset.

**Comment by aloneguid** [comment] 2017-10-12 10:49
@moggy001 thanks for the sample, reproduced and fixed it, should be on nuget in latest alpha in a few minutes.

**Comment by moggy001** [comment] 2017-10-12 11:12
Cool. Thanks :-)
