### ISSUE TITLE
Issue or question about writing parquet file with short/int16

### ISSUE THREAD

**Issue by lscott-rms** [elastacloud/parquet-dotnet#437] opened 2019-10-31 00:24 UTC
I am so glad that this library exists!! It would be wonderful to have full functionality in supporting different data types -- I'm having issues with shorts and wonder if there is some simple mistake I am making.

**Version:** 3.0.0.0

**Runtime Version:** .Net Framework v4.5

**OS:** Windows

#### Expected behavior

When writing parquets of type short or Int16, the file should be able to be read back in without errors.

#### Actual behavior

When I try to read the file back in with parquet.net, I get error 

>  System.IO.IOException: 'not a Parquet file(head is 'R1R1')'

Trying to read it in via python with Pyarrow, I get 
>Unexpected end of stream

 I am able to read/write files with only integers and floats using these methods without any problem.

### Steps to reproduce the behavior

1. Step 1: Write a parquet file like this (this part goes through without any issue):

```csharp
//( I just changed the type of the example idColumn from the elastacloud documentation)
            var idColumn = new DataColumn(
               new DataField<Int16>("id"),
               new Int16[] { 1, 2 });

            var cityColumn = new DataColumn(
               new DataField<string>("city"),
               new string[] { "London", "Derby" });

            // create file schema
            var schema = new Schema(idColumn.Field, cityColumn.Field);

            using (Stream fileStream = System.IO.File.OpenWrite("d:\\tmp\\test.parquet"))
            {
                using (var parquetWriter = new ParquetWriter(schema, fileStream))
                {
                    // create a new row group in the file
                    using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
                    {
                        groupWriter.WriteColumn(idColumn);
                        groupWriter.WriteColumn(cityColumn);
                    }
                }
            }
```
2. Step 2: try to read back in:
```csharp
//
string fileNameX = @"d:\tmp\test.parquet";
Stream fs = new FileStream(fileNameX, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
var z = ParquetReader.ReadTableFromStream(fs);
```

**Comment by gsvolt** [comment] 2019-11-12 15:14
Wanted to share my experience as well. 

I used parq (the global dotnet tool) and it reported there were no issues with the parquet file that contained a short within. 

But, as @lscott-rms pointed out, if the pyarrow based parq utility is used, it results in "Unexpected end of stream" 

Based on this knowledge, I'd say perhaps the parq global dotnet tool might also need looked at when it comes to handling short date type.

**Comment by aloneguid** [comment] 2020-01-03 10:34
Hi, I cannot reproduce this with latest parquet version, can you please try?

**Comment by aloneguid** [comment] 2020-01-08 11:42
Closing as not reproducible. Feel free to reopen when you have more info.

**Closed by aloneguid** 2020-01-08 11:42 UTC
Labels: cannot reproduce 😢

**Comment by gsvolt** [comment] 2020-01-20 19:09
This specific issue will be discussed at the new project repo [here](https://github.com/aloneguid/parquet-dotnet/issues/16)
