### ISSUE TITLE
issue with parquet reader

### ISSUE THREAD

**Issue by dimpalbhole** [elastacloud/parquet-dotnet#289] opened 2018-02-01 05:13 UTC
[parquetSample.zip](https://github.com/elastacloud/parquet-dotnet/files/1684256/parquetSample.zip)
I am getting an error while using parquet reader.
Error is {"fatal error reading column 'SN'"} and message is Unable to read beyond the end of the stream.
I have set TreatByteArrayAsString = true .

My code is:
var options = new ParquetOptions { TreatByteArrayAsString = true };
DataSet ds = ParquetReader.Read(fs, options, null);

Please check attached zip folder for the file.

**Comment by dimpalbhole** [comment] 2018-02-01 09:20
Are you able to reproduce the issue?

**Comment by aloneguid** [comment] 2018-02-01 13:32
@dimpalbhole just looking at this now.

**Comment by aloneguid** [comment] 2018-02-01 13:44
Hi @dimpalbhole. Absolutely no issues on my side so I'm closing this. You might want to reopen the issue with details suggested when you create a new issue, otherwise it will be a long guesswork.

**Comment by dimpalbhole** [comment] 2018-02-06 08:35
forgot to add one thing. I am reading a blob using  ParquetReader.Read(fs, options, null).
where fs is
Stream fs = (MyAzureBlob).OpenRead()

**Comment by aloneguid** [comment] 2018-02-06 09:24
@dimpalbhole which .net runtime/version are you using and which parquet.net library version?

**Comment by dimpalbhole** [comment] 2018-02-06 09:34
@aloneguid .Net version is 4.5.2 and parquet library is  v4.0.30319 runtime version and 2.1.2(installed version)

**Comment by dimpalbhole** [comment] 2018-02-07 10:00
Are you able to reproduce this issue?

**Comment by aloneguid** [comment] 2018-02-07 21:44
@dimpalbhole non still can't reproduce it, maybe you can attach a sample project here?

**Comment by dimpalbhole** [comment] 2018-02-08 05:43
Have you tried uploading that file as a azure blob?

**Comment by aloneguid** [comment] 2018-02-09 15:37
@dimpalbhole I'm not quite sure what azure blob has to do with parquet.

**Comment by dazfuller** [comment] 2018-02-09 15:46
@dimpalbhole I've just created a simple console app which reads a parquet file from Azure Blob as a stream in the same way you are doing and it's working okay.

https://gist.github.com/dazfuller/ffedb2ed17a1977ce56c2aac13b7896c

Are you able to read the entire file and save to disk (excluding the reading as Parquet part). Just wondering if this is a network related issue.

**Comment by dimpalbhole** [comment] 2018-02-09 15:55
Have you tried with the file which i have shared? Because i am getting this
issue only with this file, other files in the same container are getting
read.If a save this file to the local disk then i am able to read this.

**Comment by dazfuller** [comment] 2018-02-09 16:08
Okay, using that file (sorry, read straight past it originally) I can re-create the error with the following from the internal stack

>    at System.IO.MemoryStream.InternalReadInt32()
>    at System.IO.BinaryReader.ReadInt32()
>    at Parquet.Data.Concrete.StringDataTypeHandler.ReadOne(BinaryReader reader)
>    at Parquet.Data.BasicDataTypeHandler`1.Read(SchemaElement tse, BinaryReader reader, ParquetOptions formatOptions)
>    at Parquet.File.ColumnarReader.TryReadDictionaryPage(PageHeader ph, IList& dictionary)
>    at Parquet.File.ColumnarReader.Read(Int64 offset, Int64 count)
>    at Parquet.ParquetReader.Read()

**Comment by aloneguid** [comment] 2018-02-09 16:13
@dimpalbhole @dazfuller when you use `blob.OpenRead()` and start start reading the stream as parquet it's not fully downloaded from blob storage yet therefore this error. Parquet needs to read the file footer before anything else, so if you're in the middle of the file it's not the right data.

**Comment by dazfuller** [comment] 2018-02-09 16:33
I think with smaller files this works fine as it's downloaded in full prior to read (I've can get it to work anyway), but with the larger files it's as per @aloneguid says.  I've updated that Gist to work with downloading the file into a local byte array before reading and that works with the same file you've provided.

**Comment by aloneguid** [comment] 2018-02-13 13:53
Closing this as not a parquet issue.

**Closed by aloneguid** 2018-02-13 13:53 UTC
Labels: not an issue
