### ISSUE TITLE
--max-rows 10 not honored

### ISSUE THREAD

**Issue by eugeneniemand** [elastacloud/parquet-dotnet#357] opened 2018-10-22 13:25 UTC
**Version:** parq 3.1.4 global install

**Runtime Version:** .Net Core 2.1.402

**OS:** Windows

#### Expected behavior

`parq view "C:\path-to-myfile" -m 5 --max-rows 10` should display first 10 rows

#### Actual behavior

Displays all the rows and below the table it says
`Showing 0 to 11 of 11 Columns. Use Arrow Keys to Navigate. Showing 0 to 42 of 152 Rows Total. Press ENTER to quit;`

When pushing the arrow keys (Left,Up,Right) it just displays the same information again, pushing the Down arrow it exits

**Comment by aloneguid** [comment] 2018-10-22 15:02
Duplicate of #351

**Comment by aloneguid** [comment] 2018-10-22 19:17
Oops not a duplicate, @AndyCross can you have a look at this please?

**Comment by AndyCross** [comment] 2018-10-23 06:45
This is a regression in the enumeration of folds not maintaining state correctly. There were multiple approaches to this including an event and some class level variables. 

There is other work ongoing to simplify the drawing of the interactive view which will tidy this up further, but for now I've fixed the core bug.

**Closed** 2018-10-24 10:52 UTC
Labels: PARQ Global Tool 📺, bug 🐛
