### ISSUE TITLE
Complex types break Table equality

### ISSUE THREAD

**Issue by emlyn** [elastacloud/parquet-dotnet#376] opened 2018-11-14 10:43 UTC
**Version:** Parquet.Net v3.2.3

**Runtime Version:** .Net Framework v4.7

**OS:** Windows 10

#### Expected behavior

`Table.Equals()` respects value semantics, and tables with equal content therefore return true.

#### Actual behavior

Struct, map and nested list fields seem to always fail comparison.

#### Code snippet reproducing the behavior

Note: first (struct) test includes an extra data field to work around #375

```f#
  [<Fact>]
  let ``Structs are comparable``() =
    let sch = Schema([ DataField("intVal", DataType.Int32) :> Field
                       StructField("structVal", DataField("int", DataType.Int32)) :> Field ])
    
    let tbl1 = Table(sch)
    tbl1.Add(Row(1, Row(1)))

    let tbl2 = Table(sch)
    tbl2.Add(Row(1, Row(1)))

    Assert.True(tbl1.Equals(tbl2, true))
```
```
System.ArgumentException : tables are different at row 0. this: {'intVal': 1, 'structVal': {'int': 1}}, other: {'intVal': 1, 'structVal': {'int': 1}}
---- System.ArgumentException : values are not equal at position 1 (1 value(s) != 1 value(s))
```
```f#
  [<Fact>]
  let ``Maps are comparable``() =
    let sch = Schema(MapField("mapVal",
                              DataField("key", DataType.String),
                              DataField("val", DataType.Int32)))
    
    let tbl1 = Table(sch)
    tbl1.Add(Row([Row("two", 2)]))

    let tbl2 = Table(sch)
    tbl2.Add(Row([Row("two", 2)]))

    Assert.True(tbl1.Equals(tbl2, true))
```
```
System.ArgumentException : tables are different at row 0. this: {'mapVal': [{'key': 'two', 'val': 2}]}, other: {'mapVal': [{'key': 'two', 'val': 2}]}
---- System.ArgumentException : values are not equal at position 0 ([2 value(s)] != [2 value(s)])
```
```f#
  [<Fact>]
  let ``Nested lists are comparable``() =
    let sch = Schema(ListField("ints", ListField("inner", DataField("int", DataType.Int32))))
    
    let tbl1 = Table(sch)
    tbl1.Add(Row([| Row(1, 1) |]))

    let tbl2 = Table(sch)
    tbl2.Add(Row([| Row(1, 1) |]))

    Assert.True(tbl1.Equals(tbl2, true))
```
```
System.ArgumentException : tables are different at row 0. this: {'ints': [[1, 1]]}, other: {'ints': [[1, 1]]}
---- System.ArgumentException : arrays at position 0 are not equal
```

**Comment by aloneguid** [comment] 2020-01-03 10:37
Cannot reproduce, this is fixed now.

**Closed by aloneguid** 2020-01-03 10:37 UTC
