### ISSUE TITLE
Serializing Class with DateTime Property Fails via ParquetConvert.Serialize()

### ISSUE THREAD

**Issue by hakenmt** [elastacloud/parquet-dotnet#369] opened 2018-11-01 15:27 UTC
**Version:** Parquet.Net v3.2.2

**Runtime Version:** netcoreapp2.1

**OS:** Windows

#### Expected behavior

When I serialize an IEnumerable of objects that have a DateTime property, the serialization succeeds.

#### Actual behavior

Exception is thrown when serializing via:

ParquetConvert.Serialize<AthenaQueryMetric>(queries, MStreamOut);

**Message**: The added or subtracted value results in an un-representable DateTime.
Parameter name: t

**StackTrace**: 
at System.DateTime.op_Addition(DateTime d, TimeSpan t)
   at System.DateTimeOffset.get_ClockDateTime()
   at Parquet.File.Values.Primitives.NanoTime..ctor(DateTimeOffset dt) in C:\projects\parquet-dotnet\src\Parquet\File\Values\Primitives\NanoTime.cs:line 19
   at Parquet.Data.Concrete.DateTimeOffsetDataTypeHandler.WriteAsInt96(BinaryWriter writer, IList values) in C:\projects\parquet-dotnet\src\Parquet\Data\Concrete\DateTimeOffsetDataTypeHandler.cs:line 182
   at Parquet.File.DataColumnWriter.WriteColumn(DataColumn column, SchemaElement tse, IDataTypeHandler dataTypeHandler, Int32 maxRepetitionLevel, Int32 maxDefinitionLevel) in C:\projects\parquet-dotnet\src\Parquet\File\DataColumnWriter.cs:line 113
   at Parquet.File.DataColumnWriter.Write(List`1 path, DataColumn column, IDataTypeHandler dataTypeHandler) in C:\projects\parquet-dotnet\src\Parquet\File\DataColumnWriter.cs:line 50
   at Parquet.ParquetRowGroupWriter.WriteColumn(DataColumn column) in C:\projects\parquet-dotnet\src\Parquet\ParquetRowGroupWriter.cs:line 75
   at Parquet.ParquetConvert.Serialize[T](IEnumerable`1 objectInstances, Stream destination, Schema schema, CompressionMethod compressionMethod, Int32 rowGroupSize) in C:\projects\parquet-dotnet\src\Parquet\ParquetConvert.cs:line 64
   at BAMCIS.LambdaFunctions.AWSAthenaUserMetrics.Entrypoint.Exec(CloudWatchScheduledEvent request, ILambdaContext context) in D:\Users\mhaken\source\repos\AWSAthenaUserMetrics\AWSAthenaUserMetrics\Entrypoint.cs:line 229

### Steps to reproduce the behavior

Use a custom class that has DateTime properties. 
Create an IEnumerable of that class.
Call ParquetConvert.Serialize(IEnumerable, Stream, Schema);

Removing the DateTime property allows the serialization to succeed.

#### Code snippet reproducing the behavior

```csharp

        [Fact]
        public void Test()
        {
            AthenaQueryMetric Test = new AthenaQueryMetric()
            {
                QueryExecutionId = "1",
                Database = "test",
                CompletionDate = DateTime.Now
            };

            Schema PSchema = SchemaReflector.Reflect<AthenaQueryMetric>();

            using (MemoryStream MStreamOut = new MemoryStream())
            {
                ParquetConvert.Serialize<AthenaQueryMetric>(new AthenaQueryMetric2] { Test }, MStreamOut, PSchema);
            }
           
        }

public class AthenaQueryMetric
    {
        public string QueryExecutionId { get; set; }

        public string Database { get; set; }

        public DateTime CompletionDate { get; set; }
    }

```

**Comment by bryanjhogan** [comment] 2018-11-01 19:47
I was about to open an issue about his. I get the same error when serializing a POCO that contains a `DateTime`.

**Comment by aloneguid** [comment] 2018-11-05 10:06
I can confirm this is a bug, should be fixed in the next update. In the meantime you can use `DateTimeOffset` field instead of `DateTime` as a workaround.

**Comment by aloneguid** [comment] 2018-11-05 14:34
Hi, we don't really have a public roadmap as such. Generally we try to release at least monthly. There are three options here:

- You're welcome to fix it and raise a PR.
- Wait until we fix it.
- Contact parquetsupport@elastacloud.com for commercial options.

**Closed** 2020-01-08 15:57 UTC
Labels: bug 🐛

**Comment by kzeitz** [comment] 2020-12-20 18:51
So I added a DateTime field to the example 'write' function.  And I'm seeing this...
![image](https://user-images.githubusercontent.com/4561557/102721666-72f56580-42b9-11eb-9649-e6322ead5f80.png)

Does this still need fixing in the array case? Or is this a different issue?

**Comment by muehan** [comment] 2021-06-03 18:25
There is no type for DateTime in parquet: https://github.com/elastacloud/parquet-dotnet/blob/master/src/Parquet/Data/DataType.cs

My workaround is to export as string
```
var createdAt = new DataColumn(
    new DataField<string>("CreatedAt"),
    positions.Select(x => x.CreatedAt.ToString()).ToArray());
```

but I use this library for the first time, I guess there is a better way. Since I only use this for a test it's not a big problem.
