### ISSUE TITLE
New Athena issue 

### ISSUE THREAD

**Issue by we7313** [elastacloud/parquet-dotnet#193] opened 2017-08-16 15:54 UTC
It looks like the fix to run in Athena has an issues:
If you take the basic example of creating parquet with elements id & city & change the input
from:
ds.Add(1, "London");
ds.Add(2, "Derby");
to
ds.Add(1, "London");
ds.Add(2, "London");

Athena errors.
It seems that is erroring on the string column being a duplicate. This issue does not happen if you have duplicate ints.

**Comment by aloneguid** [comment] 2017-08-16 16:10
@we7313 this may be because parquet.net is switching encoding from plain to dictionary when there are duplicate values over a threshold, this is to minimize file size. I'm not sure Athena supports that, but I'll get it confirmed and come back to you.

**Comment by we7313** [comment] 2017-08-18 14:27
Is there any update on this?  If it is an encoding issue, is there a way we could force it to plain???

**Comment by xhochy** [comment] 2017-08-18 15:33
This should not be an issue with Athena as Athena (and the underlying Presto) should be able to read Dictionary encoding.

Plain and Dictionary Encoding are the two essential ones every library should definitely support.

**Comment by aloneguid** [comment] 2017-08-18 16:37
@xhochy  there seems to be slight differences in Athena and parquet-mr implementations as we always cross-check against parquet-mr. Do you know by any chance which underlying library Athena (or Presto) is using, so we can easily embed this in integration tests?

**Comment by we7313** [comment] 2017-08-18 17:44
This is what I see when I do a show table in athena:
CREATE EXTERNAL TABLE `city`(
  `id` int, 
  `city` string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://ds-parquet/city'
TBLPROPERTIES (
  'transient_lastDdlTime'='1502826620')

is that what you need?

**Comment by xhochy** [comment] 2017-08-18 18:03
@aloneguid no, sadly I have no idea but I guess some parts are custom code in Presto as Presto has a vectorized Parquet reader which parquet-mr has not yet.

Can you share one of these problematic files or try to read them with Parquet-cpp/pyarrow.parquet?

**Comment by we7313** [comment] 2017-08-18 18:48
here is the c# code to reproduce the file/problem.
  var ds = new Parquet.Data.DataSet(
                new SchemaElement<int>("id"),
                new SchemaElement<string>("city")
            );


            ds.Add(1, "London");
            ds.Add(2, "London");

            using (Stream fileStream = File.OpenWrite("c:\\city.parquet"))
            {
                using (var writer = new ParquetWriter(fileStream))
                {
                    writer.Write(ds);
                }
            }

Above is the schema for the table.

**Comment by we7313** [comment] 2017-08-18 18:58
I can read the file with parquet-dotnet as well.
The only problems appears to be in Athena.  I did some trouble shooting on creating different files and data types and it seems to come to the files with a string data type and have at lease 1 duplicate value in the strings column (like demonstrated above).

**Comment by we7313** [comment] 2017-08-21 15:13
Were you able to reproduce the problem?  Let me know if I can provide any more information.

**Comment by aloneguid** [comment] 2017-08-21 15:44
@we7313  just got to looking at this again, confirmed it's failing, I'll update you in a bit.

**Comment by aloneguid** [comment] 2017-08-21 16:13
@we7313 switching off dictionary encoding didn't really help :( We'll keep digging.

**Comment by we7313** [comment] 2017-08-21 17:57
I was able to create a parquet file with pyArrowPython
and it looks considerably different and is queryable with athena:
PAR1L  
$   London ,LondonLondon    	     &œ5 cityŒ”&< LondonLondon     $L  <               ,                  	    &´5 id ¨&Ì Œ                   $L  <                ,                   	    &Ô5 __index_level_0__ ¨&ì ¬                   L5 schema %city   %id  %__index_level_0__  <&œ5 cityŒ”&< LondonLondon    &´5 id ¨&Ì Œ                  &Ô5 __index_level_0__ ¨&ì ¬                   ä pandasø{"pandas_version": "0.20.3", "columns": [{"numpy_type": "object", "pandas_type": "unicode", "name": "city", "metadata": null}, {"numpy_type": "int64", "pandas_type": "int64", "name": "id", "metadata": null}], "index_columns": ["__index_level_0__"]} "parquet-cpp version 1.2.1-SNAPSHOT ;  PAR1


Parquet.net equavalent:
PAR1 ,         L      London ,       <Hschema % id % city%  ,&5 id 22&  &:5 city ^^&:   (Oparquet-dotnet version 1.2.0.0 (build cdf7dc07388d83cad3f0bd8f0827d8d7e7bc4e55) »   PAR1

**Comment by aloneguid** [comment] 2017-08-21 18:28
@we7313 do you mind attaching this file here? I can do binary compare

**Comment by we7313** [comment] 2017-08-21 18:31
[city-ParquetNet.txt](https://github.com/elastacloud/parquet-dotnet/files/1239811/city-ParquetNet.txt)
[City-PyArrowPython.txt](https://github.com/elastacloud/parquet-dotnet/files/1239810/City-PyArrowPython.txt)

**Comment by we7313** [comment] 2017-08-21 18:31
I uploaded the files

**Comment by aloneguid** [comment] 2017-08-21 19:35
Thanks @we7313, I'll do binary compare in the morning. We'll work some compat tests with pyarrow and fastparquet, this problem is getting old )

**Comment by aloneguid** [comment] 2017-08-22 10:01
@we7313 found the issue, just wrapping up...

**Comment by aloneguid** [comment] 2017-08-22 10:43
@we7313 this is fixed now, works both in Athena and Spark

![image](https://user-images.githubusercontent.com/3155189/29561837-e8c30302-872e-11e7-8fac-57d572dfbb13.png)

Ended up being a bug our our side with dictionary encoding implementation :( It's available in latest alpha, can you please check if it works for you? Attaching generated parquet file here just in case as well.


[fuckathena.zip](https://github.com/elastacloud/parquet-dotnet/files/1241725/fuckathena.zip)

**Comment by we7313** [comment] 2017-08-22 12:58
confirmed fixed!  Thanks, I'll run some huge payloads against it and verify.
I appreciate all the hard work.

**Closed** 2017-08-22 21:47 UTC
Labels: bug
