### ISSUE TITLE
Parquet tool cant deserialize file

### ISSUE THREAD

**Issue by kRaBby** [elastacloud/parquet-dotnet#242] opened 2017-10-13 15:21 UTC
Parquet tool cant deserialize file.
[bad.zip](https://github.com/elastacloud/parquet-dotnet/files/1383056/bad.zip)
Command line:
`parquet-tools dump bad.parquet`
Also  we found a difference between generated and based schemas:
![image](https://user-images.githubusercontent.com/3025564/31554559-9ba5580e-b046-11e7-91b1-69348e860d2e.png)

**Comment by aloneguid** [comment] 2017-10-13 15:24
Every parquet library can generate different schema so I wouldn't worry about that. We'll have a look why it doesn't deserialise. Is this bad file generated by parquet.net or another library?

**Comment by kRaBby** [comment] 2017-10-13 15:27
Yes, we generated this file with parquet.net library

**Comment by aloneguid** [comment] 2017-10-13 15:28
thanks @kRaBby can you provide any code to reproduce this?

**Comment by aloneguid** [comment] 2017-10-16 14:54
@kRaBby parquet library reads this, so this may be an issue with parquet-tools only. Can you confirm the library can read it for you? If so we may need to raise an issue in parquet-tools project.

**Comment by kRaBby** [comment] 2017-10-16 15:30
problem not only with parquet-tools but with Impala too. 
As I understand main problem with Byte type: int32 (UINT_8) for Impalas TINYINT
Schema from Impala-generated file have: int32 for TINYINT
For now, workaround is use Int32 intead of Byte .

**Comment by aloneguid** [comment] 2017-10-16 15:47
@kRaBby oh I see, thanks. We have a few issues with Impala, it often doesn't conform to parquet specs, there are a few workarounds for it already. I'll check this and get back to you.

**Comment by aloneguid** [comment] 2017-10-18 21:04
@kRaBby sorry can you point me which column specifically is a problem in that bad.zip file?

**Comment by aloneguid** [comment] 2017-10-26 16:05
Hey @kRaBby  what should we do about this one? ;)

**Comment by aloneguid** [comment] 2017-11-02 12:58
closing as cannot reproduce, feel free to reopen with more info.

**Closed by aloneguid** 2017-11-02 12:58 UTC
Labels: cannot reproduce
