### ISSUE TITLE
parq -m|--min: value is not an integer

### ISSUE THREAD

**Issue by eugeneniemand** [elastacloud/parquet-dotnet#356] opened 2018-10-22 13:20 UTC
**Version:** parq 3.1.4 global install

**Runtime Version:** .Net Core 2.1.402

**OS:** Windows

#### Expected behavior

`parq view "C:\path-to-myfile" should display first 10 rows`

#### Actual behavior

Output
```
parq v3.1.4

-m|--min: value is not an integer
```

**Comment by aloneguid** [comment] 2018-10-22 15:02
Duplicate of #351

**Closed by aloneguid** 2018-10-22 15:02 UTC
Labels: duplicate
